import { ADD_PEOPLE_ACTION, FETCH_PEOPLE_ACTION, TOGGLE_PEOPLE_MODAL_ACTION, TOGGLE_PEOPLE_MODAL_MUTATION, UPDATE_PEOPLE_ACTION } from './index'

const prefix = 'peoples'

export const FETCH_PEOPLE = `${prefix}/${FETCH_PEOPLE_ACTION}`
export const ADD_PEOPLE = `${prefix}/${ADD_PEOPLE_ACTION}`
export const UPDATE_PEOPLE = `${prefix}/${UPDATE_PEOPLE_ACTION}`
export const TOGGLE_PEOPLE_MODAL = `${prefix}/${TOGGLE_PEOPLE_MODAL_ACTION}`

export const CLOSE_PEOPLE_MODAL = `${prefix}/${TOGGLE_PEOPLE_MODAL_MUTATION}`